# -*- coding: utf-8 -*-
"""Daemon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDxzES8qQKjFMcl10gOtCDTE9bsXjxhE
"""

import os
import socket
import time
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

SOCKET_PATH = "/tmp/rlm_daemon.sock"

class RLMHandler(FileSystemEventHandler):
    def on_modified(self, event):
        if event.src_path.endswith('.py'):
            # This is where incremental re-indexing happens
            # For this version, we log the change for the MCP server to see
            print(f"[*] Live Update: {event.src_path}")

def run_server():
    if os.path.exists(SOCKET_PATH): os.remove(SOCKET_PATH)
    server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    server.bind(SOCKET_PATH)
    server.listen(5)
    while True:
        conn, _ = server.accept()
        conn.sendall(b"ALIVE")
        conn.close()

if __name__ == "__main__":
    observer = Observer()
    observer.schedule(RLMHandler(), ".", recursive=True)
    observer.start()
    print("RLM Watcher Active...")
    run_server()