# -*- coding: utf-8 -*-
"""Maps.py (The Squeezer)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ztf3aUWu3oOPnhMjt2l_zbpEF7IiQW5
"""

import ast
import argparse
from pathlib import Path

class CodeSqueezer(ast.NodeVisitor):
    def __init__(self):
        self.skeleton = []

    def visit_ClassDef(self, node):
        self.skeleton.append(f"class {node.name}:")
        self.generic_visit(node)

    def visit_FunctionDef(self, node):
        args = ast.unparse(node.args)
        doc = ast.get_docstring(node)
        self.skeleton.append(f"    def {node.name}({args}):")
        if doc: self.skeleton.append(f'        """{doc}"""')
        self.skeleton.append(f"        pass")

def squeeze(path):
    try:
        tree = ast.parse(Path(path).read_text())
        s = CodeSqueezer()
        s.visit(tree)
        return "\n".join(s.skeleton)
    except Exception as e:
        return f"Error squeezing {path}: {str(e)}"

def find_symbol(path, name):
    tree = ast.parse(Path(path).read_text())
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name == name:
            return f"{node.lineno}-{node.end_lineno}"
    return None

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", required=True)
    parser.add_argument("--mode", choices=["squeeze", "find"], default="squeeze")
    parser.add_argument("--symbol")
    args = parser.parse_args()

    if args.mode == "squeeze":
        print(squeeze(args.file))
    elif args.mode == "find" and args.symbol:
        print(find_symbol(args.file, args.symbol))